-- SQL script to create tables for Header, Row, RowIrasas, RowValue,
-- ColumnTemplate and ColumnValue for PostgreSQL.
-- Run: psql -d yourdb -f create_tables.sql

BEGIN;

CREATE TABLE IF NOT EXISTS header (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "row" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    control_methods TEXT,
    row_value_id INTEGER
    -- row_value_id references row_value.id (added later after row_value exists)
);

CREATE TABLE IF NOT EXISTS row_irasas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id INTEGER NOT NULL,
    irasas_id INTEGER NOT NULL,
    "order" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS row_value (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT,
    completed_at TIMESTAMPTZ,
    completed_by_user_id UUID NOT NULL,
    row_id INTEGER NOT NULL,
    row_irasas_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS column_template (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    row_id INTEGER NOT NULL,
    "order" INTEGER NOT NULL,
    header_id INTEGER,
    is_array BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS column_value (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    single_value NUMERIC,
    array_value NUMERIC[],
    completed_at TIMESTAMPTZ,
    row_irasas_id INTEGER NOT NULL,
    column_template_id INTEGER NOT NULL,
    completed_by_user_id UUID NOT NULL
);

-- Foreign keys (assume referenced tables like irasas exist)
ALTER TABLE IF EXISTS row_irasas
    ADD CONSTRAINT fk_row_irasas_row FOREIGN KEY (row_id) REFERENCES "row" (id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS row_irasas
    ADD CONSTRAINT fk_row_irasas_irasas FOREIGN KEY (irasas_id) REFERENCES irasas (id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS row_value
    ADD CONSTRAINT fk_rowvalue_row FOREIGN KEY (row_id) REFERENCES "row" (id) ON DELETE RESTRICT;

ALTER TABLE IF EXISTS row_value
    ADD CONSTRAINT fk_rowvalue_row_irasas FOREIGN KEY (row_irasas_id) REFERENCES row_irasas (id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS "row"
    ADD CONSTRAINT fk_row_rowvalue FOREIGN KEY (row_value_id) REFERENCES row_value (id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS column_template
    ADD CONSTRAINT fk_columntemplate_row FOREIGN KEY (row_id) REFERENCES "row" (id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS column_template
    ADD CONSTRAINT fk_columntemplate_header FOREIGN KEY (header_id) REFERENCES header (id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS column_value
    ADD CONSTRAINT fk_columnvalue_row_irasas FOREIGN KEY (row_irasas_id) REFERENCES row_irasas (id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS column_value
    ADD CONSTRAINT fk_columnvalue_columntemplate FOREIGN KEY (column_template_id) REFERENCES column_template (id) ON DELETE CASCADE;

-- Indexes to speed common lookups
CREATE INDEX IF NOT EXISTS idx_column_template_row_id ON column_template (row_id);
CREATE INDEX IF NOT EXISTS idx_column_value_row_irasas_id ON column_value (row_irasas_id);
CREATE INDEX IF NOT EXISTS idx_column_value_column_template_id ON column_value (column_template_id);
CREATE INDEX IF NOT EXISTS idx_row_value_row_id ON row_value (row_id);
CREATE INDEX IF NOT EXISTS idx_row_value_row_irasas_id ON row_value (row_irasas_id);

COMMIT;

-- Notes:
-- - If your schema already has tables like "irasas" or others, the FK statements assume they exist.
-- - Adjust ON DELETE behavior to match your domain rules (RESTRICT, CASCADE, SET NULL).
-- - For production environments prefer explicit migration tooling (EF Core Migrations, Flyway, Liquibase).
