--
-- PostgreSQL database dump
--

\restrict BqCH1rJ8H8hX3j5kIIinAfFNVWyUkTeaom6ZqEiT8937tUdjANwyLKxkE2ysEB2

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-08-11 15:22:01 EEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3788 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 952 (class 1247 OID 16694)
-- Name: testotipas; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.testotipas AS ENUM (
    'testas',
    'isvezimas',
    'pakavimas'
);


ALTER TYPE public.testotipas OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 253 (class 1259 OID 16967)
-- Name: column_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.column_template (
    id integer NOT NULL,
    description text NOT NULL,
    row_id integer NOT NULL,
    "order" integer NOT NULL,
    header_id integer,
    is_array boolean DEFAULT false NOT NULL,
    array_length integer
);


ALTER TABLE public.column_template OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 16966)
-- Name: column_template_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.column_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.column_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16913)
-- Name: column_value; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.column_value (
    id integer NOT NULL,
    single_value numeric,
    array_value numeric[],
    completed_at timestamp with time zone,
    row_irasas_id integer NOT NULL,
    column_template_id integer NOT NULL,
    completed_by_user_id uuid
);


ALTER TABLE public.column_value OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16912)
-- Name: column_value_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.column_value ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.column_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 17031)
-- Name: fat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fat (
    id integer NOT NULL,
    title text NOT NULL
);


ALTER TABLE public.fat OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 17030)
-- Name: fat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fat_id_seq OWNER TO postgres;

--
-- TOC entry 3789 (class 0 OID 0)
-- Dependencies: 254
-- Name: fat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fat_id_seq OWNED BY public.fat.id;


--
-- TOC entry 256 (class 1259 OID 17041)
-- Name: fat_row; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fat_row (
    fatid integer NOT NULL,
    rowid integer NOT NULL,
    "order" integer NOT NULL
);


ALTER TABLE public.fat_row OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 17066)
-- Name: fatreport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fatreport (
    id integer NOT NULL,
    text text NOT NULL
);


ALTER TABLE public.fatreport OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 17065)
-- Name: fatreport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fatreport_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fatreport_id_seq OWNER TO postgres;

--
-- TOC entry 3790 (class 0 OID 0)
-- Dependencies: 257
-- Name: fatreport_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fatreport_id_seq OWNED BY public.fatreport.id;


--
-- TOC entry 262 (class 1259 OID 17095)
-- Name: fatreport_irasas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fatreport_irasas (
    id integer NOT NULL,
    fatreport_id integer,
    irasasid integer,
    "order" integer
);


ALTER TABLE public.fatreport_irasas OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 17094)
-- Name: fatreport_irasas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fatreport_irasas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fatreport_irasas_id_seq OWNER TO postgres;

--
-- TOC entry 3791 (class 0 OID 0)
-- Dependencies: 261
-- Name: fatreport_irasas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fatreport_irasas_id_seq OWNED BY public.fatreport_irasas.id;


--
-- TOC entry 247 (class 1259 OID 16935)
-- Name: header; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.header (
    id integer NOT NULL,
    text text NOT NULL,
    row_id integer NOT NULL
);


ALTER TABLE public.header OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16934)
-- Name: header_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.header ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.header_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16608)
-- Name: irasas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.irasas (
    id integer NOT NULL,
    id_dokumento text NOT NULL,
    pavadinimas text NOT NULL,
    pradzia date,
    pabaiga date,
    statusas text,
    lokacija_id integer
);


ALTER TABLE public.irasas OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16618)
-- Name: irasas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.irasas ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.irasas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16774)
-- Name: lokacija; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lokacija (
    id integer NOT NULL,
    pavadinimas text NOT NULL
);


ALTER TABLE public.lokacija OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16773)
-- Name: lokacija_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.lokacija_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.lokacija_id_seq OWNER TO postgres;

--
-- TOC entry 3792 (class 0 OID 0)
-- Dependencies: 233
-- Name: lokacija_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.lokacija_id_seq OWNED BY public.lokacija.id;


--
-- TOC entry 222 (class 1259 OID 16619)
-- Name: naudotojas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.naudotojas (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    vardas character varying(30) NOT NULL,
    pavarde character varying(30) NOT NULL,
    gimimo_data date NOT NULL,
    adminas boolean DEFAULT false NOT NULL,
    password_hash character varying(200) NOT NULL,
    prisijungimoid text,
    super_adminas boolean,
    must_change_password boolean DEFAULT false NOT NULL
);


ALTER TABLE public.naudotojas OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16839)
-- Name: naudotojas_zinute; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.naudotojas_zinute (
    zinute_id integer NOT NULL,
    naudotojas_id uuid NOT NULL,
    perskaityta boolean
);


ALTER TABLE public.naudotojas_zinute OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16632)
-- Name: prisegtasfailas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prisegtasfailas (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    failopav text,
    dydis bigint,
    nuoroda text,
    sukurimolaikas date,
    zingsnis_id integer,
    zingsnis_template_id integer
);


ALTER TABLE public.prisegtasfailas OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16639)
-- Name: refreshtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refreshtoken (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    token text NOT NULL,
    expires date NOT NULL,
    revoked date,
    naudotojasid uuid
);


ALTER TABLE public.refreshtoken OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 17077)
-- Name: report_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report_template (
    id integer NOT NULL,
    text text NOT NULL,
    fatreport_id integer NOT NULL,
    "order" integer NOT NULL
);


ALTER TABLE public.report_template OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 17076)
-- Name: report_template_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.report_template_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.report_template_id_seq OWNER TO postgres;

--
-- TOC entry 3793 (class 0 OID 0)
-- Dependencies: 259
-- Name: report_template_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.report_template_id_seq OWNED BY public.report_template.id;


--
-- TOC entry 264 (class 1259 OID 17113)
-- Name: report_value; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report_value (
    id integer NOT NULL,
    value text NOT NULL,
    fatreport_irasasid integer NOT NULL,
    report_template_id integer NOT NULL
);


ALTER TABLE public.report_value OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 17112)
-- Name: report_value_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.report_value_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.report_value_id_seq OWNER TO postgres;

--
-- TOC entry 3794 (class 0 OID 0)
-- Dependencies: 263
-- Name: report_value_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.report_value_id_seq OWNED BY public.report_value.id;


--
-- TOC entry 245 (class 1259 OID 16925)
-- Name: row; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."row" (
    id integer NOT NULL,
    description text NOT NULL,
    control_methods text
);


ALTER TABLE public."row" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16924)
-- Name: row_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."row" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.row_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 16945)
-- Name: row_irasas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.row_irasas (
    id integer NOT NULL,
    row_id integer NOT NULL,
    irasas_id integer NOT NULL,
    "order" integer NOT NULL
);


ALTER TABLE public.row_irasas OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16944)
-- Name: row_irasas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.row_irasas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.row_irasas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 16955)
-- Name: row_value; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.row_value (
    id integer NOT NULL,
    value text,
    completed_at timestamp with time zone,
    completed_by_user_id uuid,
    row_id integer NOT NULL,
    row_irasas_id integer NOT NULL
);


ALTER TABLE public.row_value OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 16954)
-- Name: row_value_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.row_value ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.row_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16790)
-- Name: sablonas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sablonas (
    id integer NOT NULL,
    pavadinimas text NOT NULL
);


ALTER TABLE public.sablonas OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16789)
-- Name: sablonas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.sablonas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sablonas_id_seq OWNER TO postgres;

--
-- TOC entry 3795 (class 0 OID 0)
-- Dependencies: 235
-- Name: sablonas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.sablonas_id_seq OWNED BY public.sablonas.id;


--
-- TOC entry 237 (class 1259 OID 16801)
-- Name: sablonas_testas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sablonas_testas (
    testasid integer NOT NULL,
    sablonasid integer NOT NULL,
    eile integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.sablonas_testas OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16648)
-- Name: testas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.testas (
    id integer NOT NULL,
    testotekstas text NOT NULL,
    tipas public.testotipas
);


ALTER TABLE public.testas OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16655)
-- Name: testas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.testas ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.testas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16656)
-- Name: testasirasas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.testasirasas (
    testasid integer NOT NULL,
    irasasid integer NOT NULL,
    id integer NOT NULL,
    eile integer
);


ALTER TABLE public.testasirasas OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16751)
-- Name: testasirasas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.testasirasas ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.testasirasas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16860)
-- Name: testasirasas_privalomas_zingsnis_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.testasirasas_privalomas_zingsnis_template (
    testasirasas_id integer CONSTRAINT testasirasas_privalomas_zingsnis_templ_testasirasas_id_not_null NOT NULL,
    zingsnis_template_id integer CONSTRAINT testasirasas_privalomas_zingsnis__zingsnis_template_id_not_null NOT NULL
);


ALTER TABLE public.testasirasas_privalomas_zingsnis_template OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16712)
-- Name: zingsnis; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zingsnis (
    id integer NOT NULL,
    komentaras text NOT NULL,
    irasas_testas_id integer,
    zingsnis_template_id integer,
    completed_by_user_id uuid,
    completed_at timestamp without time zone
);


ALTER TABLE public.zingsnis OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16772)
-- Name: zingsnis_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zingsnis ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.zingsnis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16733)
-- Name: zingsnis_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zingsnis_template (
    id integer NOT NULL,
    testas_id integer,
    pavadinimas text,
    aprasymas text,
    eile integer,
    nuotrauka_privaloma boolean,
    komentaras_privalomas boolean
);


ALTER TABLE public.zingsnis_template OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16771)
-- Name: zingsnis_template_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zingsnis_template ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.zingsnis_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16829)
-- Name: zinute; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zinute (
    id integer NOT NULL,
    tekstas text NOT NULL
);


ALTER TABLE public.zinute OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16828)
-- Name: zinute_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.zinute_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.zinute_id_seq OWNER TO postgres;

--
-- TOC entry 3796 (class 0 OID 0)
-- Dependencies: 238
-- Name: zinute_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.zinute_id_seq OWNED BY public.zinute.id;


--
-- TOC entry 3495 (class 2604 OID 17034)
-- Name: fat id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fat ALTER COLUMN id SET DEFAULT nextval('public.fat_id_seq'::regclass);


--
-- TOC entry 3496 (class 2604 OID 17069)
-- Name: fatreport id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fatreport ALTER COLUMN id SET DEFAULT nextval('public.fatreport_id_seq'::regclass);


--
-- TOC entry 3498 (class 2604 OID 17098)
-- Name: fatreport_irasas id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fatreport_irasas ALTER COLUMN id SET DEFAULT nextval('public.fatreport_irasas_id_seq'::regclass);


--
-- TOC entry 3490 (class 2604 OID 16777)
-- Name: lokacija id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lokacija ALTER COLUMN id SET DEFAULT nextval('public.lokacija_id_seq'::regclass);


--
-- TOC entry 3497 (class 2604 OID 17080)
-- Name: report_template id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_template ALTER COLUMN id SET DEFAULT nextval('public.report_template_id_seq'::regclass);


--
-- TOC entry 3499 (class 2604 OID 17116)
-- Name: report_value id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_value ALTER COLUMN id SET DEFAULT nextval('public.report_value_id_seq'::regclass);


--
-- TOC entry 3491 (class 2604 OID 16793)
-- Name: sablonas id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sablonas ALTER COLUMN id SET DEFAULT nextval('public.sablonas_id_seq'::regclass);


--
-- TOC entry 3493 (class 2604 OID 16832)
-- Name: zinute id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zinute ALTER COLUMN id SET DEFAULT nextval('public.zinute_id_seq'::regclass);


--
-- TOC entry 3771 (class 0 OID 16967)
-- Dependencies: 253
-- Data for Name: column_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.column_template (id, description, row_id, "order", header_id, is_array, array_length) FROM stdin;
\.


--
-- TOC entry 3761 (class 0 OID 16913)
-- Dependencies: 243
-- Data for Name: column_value; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.column_value (id, single_value, array_value, completed_at, row_irasas_id, column_template_id, completed_by_user_id) FROM stdin;
\.


--
-- TOC entry 3773 (class 0 OID 17031)
-- Dependencies: 255
-- Data for Name: fat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fat (id, title) FROM stdin;
\.


--
-- TOC entry 3774 (class 0 OID 17041)
-- Dependencies: 256
-- Data for Name: fat_row; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fat_row (fatid, rowid, "order") FROM stdin;
\.


--
-- TOC entry 3776 (class 0 OID 17066)
-- Dependencies: 258
-- Data for Name: fatreport; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fatreport (id, text) FROM stdin;
\.


--
-- TOC entry 3780 (class 0 OID 17095)
-- Dependencies: 262
-- Data for Name: fatreport_irasas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fatreport_irasas (id, fatreport_id, irasasid, "order") FROM stdin;
\.


--
-- TOC entry 3765 (class 0 OID 16935)
-- Dependencies: 247
-- Data for Name: header; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.header (id, text, row_id) FROM stdin;
\.


--
-- TOC entry 3738 (class 0 OID 16608)
-- Dependencies: 220
-- Data for Name: irasas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.irasas (id, id_dokumento, pavadinimas, pradzia, pabaiga, statusas, lokacija_id) FROM stdin;
\.


--
-- TOC entry 3752 (class 0 OID 16774)
-- Dependencies: 234
-- Data for Name: lokacija; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lokacija (id, pavadinimas) FROM stdin;
\.


--
-- TOC entry 3740 (class 0 OID 16619)
-- Dependencies: 222
-- Data for Name: naudotojas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.naudotojas (id, vardas, pavarde, gimimo_data, adminas, password_hash, prisijungimoid, super_adminas, must_change_password) FROM stdin;
3fa85f64-5717-4562-b3fc-2c963f66afa6	Super	Admin	2026-02-21	t	$2a$11$XOluA5qHy5wV7Y.twmVgLOjO3EvrsWAfk2ypmioAk1D0T.SWoEJjS	SuperAdmin	t	f
\.


--
-- TOC entry 3758 (class 0 OID 16839)
-- Dependencies: 240
-- Data for Name: naudotojas_zinute; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.naudotojas_zinute (zinute_id, naudotojas_id, perskaityta) FROM stdin;
\.


--
-- TOC entry 3741 (class 0 OID 16632)
-- Dependencies: 223
-- Data for Name: prisegtasfailas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prisegtasfailas (id, failopav, dydis, nuoroda, sukurimolaikas, zingsnis_id, zingsnis_template_id) FROM stdin;
\.


--
-- TOC entry 3742 (class 0 OID 16639)
-- Dependencies: 224
-- Data for Name: refreshtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refreshtoken (id, token, expires, revoked, naudotojasid) FROM stdin;
\.


--
-- TOC entry 3778 (class 0 OID 17077)
-- Dependencies: 260
-- Data for Name: report_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.report_template (id, text, fatreport_id, "order") FROM stdin;
\.


--
-- TOC entry 3782 (class 0 OID 17113)
-- Dependencies: 264
-- Data for Name: report_value; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.report_value (id, value, fatreport_irasasid, report_template_id) FROM stdin;
\.


--
-- TOC entry 3763 (class 0 OID 16925)
-- Dependencies: 245
-- Data for Name: row; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."row" (id, description, control_methods) FROM stdin;
\.


--
-- TOC entry 3767 (class 0 OID 16945)
-- Dependencies: 249
-- Data for Name: row_irasas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.row_irasas (id, row_id, irasas_id, "order") FROM stdin;
\.


--
-- TOC entry 3769 (class 0 OID 16955)
-- Dependencies: 251
-- Data for Name: row_value; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.row_value (id, value, completed_at, completed_by_user_id, row_id, row_irasas_id) FROM stdin;
\.


--
-- TOC entry 3754 (class 0 OID 16790)
-- Dependencies: 236
-- Data for Name: sablonas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sablonas (id, pavadinimas) FROM stdin;
\.


--
-- TOC entry 3755 (class 0 OID 16801)
-- Dependencies: 237
-- Data for Name: sablonas_testas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sablonas_testas (testasid, sablonasid, eile) FROM stdin;
\.


--
-- TOC entry 3743 (class 0 OID 16648)
-- Dependencies: 225
-- Data for Name: testas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.testas (id, testotekstas, tipas) FROM stdin;
\.


--
-- TOC entry 3745 (class 0 OID 16656)
-- Dependencies: 227
-- Data for Name: testasirasas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.testasirasas (testasid, irasasid, id, eile) FROM stdin;
\.


--
-- TOC entry 3759 (class 0 OID 16860)
-- Dependencies: 241
-- Data for Name: testasirasas_privalomas_zingsnis_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.testasirasas_privalomas_zingsnis_template (testasirasas_id, zingsnis_template_id) FROM stdin;
\.


--
-- TOC entry 3746 (class 0 OID 16712)
-- Dependencies: 228
-- Data for Name: zingsnis; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zingsnis (id, komentaras, irasas_testas_id, zingsnis_template_id, completed_by_user_id, completed_at) FROM stdin;
\.


--
-- TOC entry 3747 (class 0 OID 16733)
-- Dependencies: 229
-- Data for Name: zingsnis_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zingsnis_template (id, testas_id, pavadinimas, aprasymas, eile, nuotrauka_privaloma, komentaras_privalomas) FROM stdin;
\.


--
-- TOC entry 3757 (class 0 OID 16829)
-- Dependencies: 239
-- Data for Name: zinute; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zinute (id, tekstas) FROM stdin;
\.


--
-- TOC entry 3797 (class 0 OID 0)
-- Dependencies: 252
-- Name: column_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.column_template_id_seq', 15, true);


--
-- TOC entry 3798 (class 0 OID 0)
-- Dependencies: 242
-- Name: column_value_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.column_value_id_seq', 11, true);


--
-- TOC entry 3799 (class 0 OID 0)
-- Dependencies: 254
-- Name: fat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fat_id_seq', 4, true);


--
-- TOC entry 3800 (class 0 OID 0)
-- Dependencies: 257
-- Name: fatreport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fatreport_id_seq', 1, true);


--
-- TOC entry 3801 (class 0 OID 0)
-- Dependencies: 261
-- Name: fatreport_irasas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fatreport_irasas_id_seq', 1, true);


--
-- TOC entry 3802 (class 0 OID 0)
-- Dependencies: 246
-- Name: header_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.header_id_seq', 8, true);


--
-- TOC entry 3803 (class 0 OID 0)
-- Dependencies: 221
-- Name: irasas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.irasas_id_seq', 25, true);


--
-- TOC entry 3804 (class 0 OID 0)
-- Dependencies: 233
-- Name: lokacija_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lokacija_id_seq', 15, true);


--
-- TOC entry 3805 (class 0 OID 0)
-- Dependencies: 259
-- Name: report_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.report_template_id_seq', 5, true);


--
-- TOC entry 3806 (class 0 OID 0)
-- Dependencies: 263
-- Name: report_value_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.report_value_id_seq', 1, true);


--
-- TOC entry 3807 (class 0 OID 0)
-- Dependencies: 244
-- Name: row_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.row_id_seq', 10, true);


--
-- TOC entry 3808 (class 0 OID 0)
-- Dependencies: 248
-- Name: row_irasas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.row_irasas_id_seq', 14, true);


--
-- TOC entry 3809 (class 0 OID 0)
-- Dependencies: 250
-- Name: row_value_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.row_value_id_seq', 6, true);


--
-- TOC entry 3810 (class 0 OID 0)
-- Dependencies: 235
-- Name: sablonas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sablonas_id_seq', 6, true);


--
-- TOC entry 3811 (class 0 OID 0)
-- Dependencies: 226
-- Name: testas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.testas_id_seq', 23, true);


--
-- TOC entry 3812 (class 0 OID 0)
-- Dependencies: 230
-- Name: testasirasas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.testasirasas_id_seq', 26, true);


--
-- TOC entry 3813 (class 0 OID 0)
-- Dependencies: 232
-- Name: zingsnis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zingsnis_id_seq', 25, true);


--
-- TOC entry 3814 (class 0 OID 0)
-- Dependencies: 231
-- Name: zingsnis_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zingsnis_template_id_seq', 56, true);


--
-- TOC entry 3815 (class 0 OID 0)
-- Dependencies: 238
-- Name: zinute_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zinute_id_seq', 4, true);


--
-- TOC entry 3545 (class 2606 OID 16979)
-- Name: column_template column_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.column_template
    ADD CONSTRAINT column_template_pkey PRIMARY KEY (id);


--
-- TOC entry 3531 (class 2606 OID 16923)
-- Name: column_value column_value_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.column_value
    ADD CONSTRAINT column_value_pkey PRIMARY KEY (id);


--
-- TOC entry 3548 (class 2606 OID 17040)
-- Name: fat fat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fat
    ADD CONSTRAINT fat_pkey PRIMARY KEY (id);


--
-- TOC entry 3550 (class 2606 OID 17048)
-- Name: fat_row fat_row_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fat_row
    ADD CONSTRAINT fat_row_pkey PRIMARY KEY (fatid, rowid);


--
-- TOC entry 3556 (class 2606 OID 17101)
-- Name: fatreport_irasas fatreport_irasas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fatreport_irasas
    ADD CONSTRAINT fatreport_irasas_pkey PRIMARY KEY (id);


--
-- TOC entry 3552 (class 2606 OID 17075)
-- Name: fatreport fatreport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fatreport
    ADD CONSTRAINT fatreport_pkey PRIMARY KEY (id);


--
-- TOC entry 3537 (class 2606 OID 16943)
-- Name: header header_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.header
    ADD CONSTRAINT header_pkey PRIMARY KEY (id);


--
-- TOC entry 3501 (class 2606 OID 16662)
-- Name: irasas irasas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.irasas
    ADD CONSTRAINT irasas_pkey PRIMARY KEY (id);


--
-- TOC entry 3519 (class 2606 OID 16783)
-- Name: lokacija lokacija_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lokacija
    ADD CONSTRAINT lokacija_pkey PRIMARY KEY (id);


--
-- TOC entry 3503 (class 2606 OID 16664)
-- Name: naudotojas naudotojas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.naudotojas
    ADD CONSTRAINT naudotojas_pkey PRIMARY KEY (id);


--
-- TOC entry 3527 (class 2606 OID 16845)
-- Name: naudotojas_zinute naudotojas_zinute_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.naudotojas_zinute
    ADD CONSTRAINT naudotojas_zinute_pkey PRIMARY KEY (zinute_id, naudotojas_id);


--
-- TOC entry 3529 (class 2606 OID 16866)
-- Name: testasirasas_privalomas_zingsnis_template pk_testasirasas_privalomas_zingsnis_template; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testasirasas_privalomas_zingsnis_template
    ADD CONSTRAINT pk_testasirasas_privalomas_zingsnis_template PRIMARY KEY (testasirasas_id, zingsnis_template_id);


--
-- TOC entry 3505 (class 2606 OID 16666)
-- Name: prisegtasfailas prisegtasfailas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prisegtasfailas
    ADD CONSTRAINT prisegtasfailas_pkey PRIMARY KEY (id);


--
-- TOC entry 3507 (class 2606 OID 16668)
-- Name: refreshtoken refreshtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT refreshtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 3554 (class 2606 OID 17088)
-- Name: report_template report_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_template
    ADD CONSTRAINT report_template_pkey PRIMARY KEY (id);


--
-- TOC entry 3558 (class 2606 OID 17124)
-- Name: report_value report_value_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_value
    ADD CONSTRAINT report_value_pkey PRIMARY KEY (id);


--
-- TOC entry 3539 (class 2606 OID 16953)
-- Name: row_irasas row_irasas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.row_irasas
    ADD CONSTRAINT row_irasas_pkey PRIMARY KEY (id);


--
-- TOC entry 3535 (class 2606 OID 16933)
-- Name: row row_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."row"
    ADD CONSTRAINT row_pkey PRIMARY KEY (id);


--
-- TOC entry 3543 (class 2606 OID 16965)
-- Name: row_value row_value_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.row_value
    ADD CONSTRAINT row_value_pkey PRIMARY KEY (id);


--
-- TOC entry 3521 (class 2606 OID 16799)
-- Name: sablonas sablonas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sablonas
    ADD CONSTRAINT sablonas_pkey PRIMARY KEY (id);


--
-- TOC entry 3523 (class 2606 OID 16807)
-- Name: sablonas_testas sablonas_testas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sablonas_testas
    ADD CONSTRAINT sablonas_testas_pkey PRIMARY KEY (testasid, sablonasid);


--
-- TOC entry 3509 (class 2606 OID 16670)
-- Name: testas testas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testas
    ADD CONSTRAINT testas_pkey PRIMARY KEY (id);


--
-- TOC entry 3511 (class 2606 OID 16758)
-- Name: testasirasas testasirasas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testasirasas
    ADD CONSTRAINT testasirasas_pkey PRIMARY KEY (id);


--
-- TOC entry 3513 (class 2606 OID 16760)
-- Name: testasirasas testasirasas_testasid_irasasid_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testasirasas
    ADD CONSTRAINT testasirasas_testasid_irasasid_unique UNIQUE (testasid, irasasid);


--
-- TOC entry 3515 (class 2606 OID 16722)
-- Name: zingsnis zingsnis_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zingsnis
    ADD CONSTRAINT zingsnis_pkey PRIMARY KEY (id);


--
-- TOC entry 3517 (class 2606 OID 16740)
-- Name: zingsnis_template zingsnis_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zingsnis_template
    ADD CONSTRAINT zingsnis_template_pkey PRIMARY KEY (id);


--
-- TOC entry 3525 (class 2606 OID 16838)
-- Name: zinute zinute_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zinute
    ADD CONSTRAINT zinute_pkey PRIMARY KEY (id);


--
-- TOC entry 3546 (class 1259 OID 17025)
-- Name: idx_column_template_row_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_column_template_row_id ON public.column_template USING btree (row_id);


--
-- TOC entry 3532 (class 1259 OID 17027)
-- Name: idx_column_value_column_template_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_column_value_column_template_id ON public.column_value USING btree (column_template_id);


--
-- TOC entry 3533 (class 1259 OID 17026)
-- Name: idx_column_value_row_irasas_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_column_value_row_irasas_id ON public.column_value USING btree (row_irasas_id);


--
-- TOC entry 3540 (class 1259 OID 17028)
-- Name: idx_row_value_row_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_row_value_row_id ON public.row_value USING btree (row_id);


--
-- TOC entry 3541 (class 1259 OID 17029)
-- Name: idx_row_value_row_irasas_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_row_value_row_irasas_id ON public.row_value USING btree (row_irasas_id);


--
-- TOC entry 3582 (class 2606 OID 17010)
-- Name: column_template fk_columntemplate_header; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.column_template
    ADD CONSTRAINT fk_columntemplate_header FOREIGN KEY (header_id) REFERENCES public.header(id) ON DELETE SET NULL;


--
-- TOC entry 3583 (class 2606 OID 17005)
-- Name: column_template fk_columntemplate_row; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.column_template
    ADD CONSTRAINT fk_columntemplate_row FOREIGN KEY (row_id) REFERENCES public."row"(id) ON DELETE CASCADE;


--
-- TOC entry 3575 (class 2606 OID 17020)
-- Name: column_value fk_columnvalue_columntemplate; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.column_value
    ADD CONSTRAINT fk_columnvalue_columntemplate FOREIGN KEY (column_template_id) REFERENCES public.column_template(id) ON DELETE CASCADE;


--
-- TOC entry 3576 (class 2606 OID 17015)
-- Name: column_value fk_columnvalue_row_irasas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.column_value
    ADD CONSTRAINT fk_columnvalue_row_irasas FOREIGN KEY (row_irasas_id) REFERENCES public.row_irasas(id) ON DELETE CASCADE;


--
-- TOC entry 3584 (class 2606 OID 17049)
-- Name: fat_row fk_fat_row_fat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fat_row
    ADD CONSTRAINT fk_fat_row_fat FOREIGN KEY (fatid) REFERENCES public.fat(id) ON DELETE CASCADE;


--
-- TOC entry 3585 (class 2606 OID 17054)
-- Name: fat_row fk_fat_row_row; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fat_row
    ADD CONSTRAINT fk_fat_row_row FOREIGN KEY (rowid) REFERENCES public."row"(id);


--
-- TOC entry 3587 (class 2606 OID 17102)
-- Name: fatreport_irasas fk_fatreportirasas_fatreport; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fatreport_irasas
    ADD CONSTRAINT fk_fatreportirasas_fatreport FOREIGN KEY (fatreport_id) REFERENCES public.fatreport(id) ON DELETE CASCADE;


--
-- TOC entry 3588 (class 2606 OID 17107)
-- Name: fatreport_irasas fk_fatreportirasas_irasas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fatreport_irasas
    ADD CONSTRAINT fk_fatreportirasas_irasas FOREIGN KEY (irasasid) REFERENCES public.irasas(id) ON DELETE CASCADE;


--
-- TOC entry 3565 (class 2606 OID 16761)
-- Name: zingsnis fk_irasastekstas_zingsnis; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zingsnis
    ADD CONSTRAINT fk_irasastekstas_zingsnis FOREIGN KEY (irasas_testas_id) REFERENCES public.testasirasas(id) ON DELETE CASCADE;


--
-- TOC entry 3559 (class 2606 OID 16784)
-- Name: irasas fk_lokacija; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.irasas
    ADD CONSTRAINT fk_lokacija FOREIGN KEY (lokacija_id) REFERENCES public.lokacija(id);


--
-- TOC entry 3566 (class 2606 OID 16766)
-- Name: zingsnis fk_naudotojas_zingsnis; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zingsnis
    ADD CONSTRAINT fk_naudotojas_zingsnis FOREIGN KEY (completed_by_user_id) REFERENCES public.naudotojas(id) ON DELETE CASCADE;


--
-- TOC entry 3560 (class 2606 OID 16728)
-- Name: prisegtasfailas fk_prisegtas_zingsnis; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prisegtasfailas
    ADD CONSTRAINT fk_prisegtas_zingsnis FOREIGN KEY (zingsnis_id) REFERENCES public.zingsnis(id) ON DELETE CASCADE;


--
-- TOC entry 3586 (class 2606 OID 17089)
-- Name: report_template fk_reporttemplate_fatreport; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_template
    ADD CONSTRAINT fk_reporttemplate_fatreport FOREIGN KEY (fatreport_id) REFERENCES public.fatreport(id) ON DELETE CASCADE;


--
-- TOC entry 3589 (class 2606 OID 17125)
-- Name: report_value fk_reportvalue_fatreportirasas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_value
    ADD CONSTRAINT fk_reportvalue_fatreportirasas FOREIGN KEY (fatreport_irasasid) REFERENCES public.fatreport_irasas(id) ON DELETE CASCADE;


--
-- TOC entry 3590 (class 2606 OID 17130)
-- Name: report_value fk_reportvalue_reporttemplate; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report_value
    ADD CONSTRAINT fk_reportvalue_reporttemplate FOREIGN KEY (report_template_id) REFERENCES public.report_template(id) ON DELETE CASCADE;


--
-- TOC entry 3578 (class 2606 OID 16985)
-- Name: row_irasas fk_row_irasas_irasas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.row_irasas
    ADD CONSTRAINT fk_row_irasas_irasas FOREIGN KEY (irasas_id) REFERENCES public.irasas(id) ON DELETE CASCADE;


--
-- TOC entry 3579 (class 2606 OID 16980)
-- Name: row_irasas fk_row_irasas_row; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.row_irasas
    ADD CONSTRAINT fk_row_irasas_row FOREIGN KEY (row_id) REFERENCES public."row"(id) ON DELETE CASCADE;


--
-- TOC entry 3580 (class 2606 OID 16990)
-- Name: row_value fk_rowvalue_row; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.row_value
    ADD CONSTRAINT fk_rowvalue_row FOREIGN KEY (row_id) REFERENCES public."row"(id) ON DELETE RESTRICT;


--
-- TOC entry 3581 (class 2606 OID 16995)
-- Name: row_value fk_rowvalue_row_irasas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.row_value
    ADD CONSTRAINT fk_rowvalue_row_irasas FOREIGN KEY (row_irasas_id) REFERENCES public.row_irasas(id) ON DELETE CASCADE;


--
-- TOC entry 3568 (class 2606 OID 16741)
-- Name: zingsnis_template fk_template_testas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zingsnis_template
    ADD CONSTRAINT fk_template_testas FOREIGN KEY (testas_id) REFERENCES public.testas(id) ON DELETE CASCADE;


--
-- TOC entry 3567 (class 2606 OID 16746)
-- Name: zingsnis fk_template_zingsnis; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zingsnis
    ADD CONSTRAINT fk_template_zingsnis FOREIGN KEY (zingsnis_template_id) REFERENCES public.zingsnis_template(id) ON DELETE CASCADE;


--
-- TOC entry 3573 (class 2606 OID 16872)
-- Name: testasirasas_privalomas_zingsnis_template fk_tipzt_testasirasas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testasirasas_privalomas_zingsnis_template
    ADD CONSTRAINT fk_tipzt_testasirasas FOREIGN KEY (testasirasas_id) REFERENCES public.testasirasas(id) ON DELETE CASCADE;


--
-- TOC entry 3574 (class 2606 OID 16867)
-- Name: testasirasas_privalomas_zingsnis_template fk_tipzt_zingsnis_template; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testasirasas_privalomas_zingsnis_template
    ADD CONSTRAINT fk_tipzt_zingsnis_template FOREIGN KEY (zingsnis_template_id) REFERENCES public.zingsnis_template(id) ON DELETE CASCADE;


--
-- TOC entry 3577 (class 2606 OID 17059)
-- Name: header header_row_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.header
    ADD CONSTRAINT header_row_id_fkey FOREIGN KEY (row_id) REFERENCES public."row"(id);


--
-- TOC entry 3571 (class 2606 OID 16851)
-- Name: naudotojas_zinute naudotojas_zinute_naudotojas_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.naudotojas_zinute
    ADD CONSTRAINT naudotojas_zinute_naudotojas_id_fkey FOREIGN KEY (naudotojas_id) REFERENCES public.naudotojas(id);


--
-- TOC entry 3572 (class 2606 OID 16846)
-- Name: naudotojas_zinute naudotojas_zinute_zinute_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.naudotojas_zinute
    ADD CONSTRAINT naudotojas_zinute_zinute_id_fkey FOREIGN KEY (zinute_id) REFERENCES public.zinute(id);


--
-- TOC entry 3561 (class 2606 OID 16823)
-- Name: prisegtasfailas prisegtasfailas_zingsnis_template_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prisegtasfailas
    ADD CONSTRAINT prisegtasfailas_zingsnis_template_id_fkey FOREIGN KEY (zingsnis_template_id) REFERENCES public.zingsnis_template(id) ON DELETE CASCADE;


--
-- TOC entry 3562 (class 2606 OID 16678)
-- Name: refreshtoken refreshtoken_naudotojasid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT refreshtoken_naudotojasid_fkey FOREIGN KEY (naudotojasid) REFERENCES public.naudotojas(id) ON DELETE CASCADE;


--
-- TOC entry 3569 (class 2606 OID 16818)
-- Name: sablonas_testas sablonas_testas_sablonasid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sablonas_testas
    ADD CONSTRAINT sablonas_testas_sablonasid_fkey FOREIGN KEY (sablonasid) REFERENCES public.sablonas(id) ON DELETE CASCADE;


--
-- TOC entry 3570 (class 2606 OID 16808)
-- Name: sablonas_testas sablonas_testas_testasid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sablonas_testas
    ADD CONSTRAINT sablonas_testas_testasid_fkey FOREIGN KEY (testasid) REFERENCES public.testas(id);


--
-- TOC entry 3563 (class 2606 OID 16683)
-- Name: testasirasas testasirasas_irasasid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testasirasas
    ADD CONSTRAINT testasirasas_irasasid_fkey FOREIGN KEY (irasasid) REFERENCES public.irasas(id) ON DELETE CASCADE;


--
-- TOC entry 3564 (class 2606 OID 16688)
-- Name: testasirasas testasirasas_testasid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.testasirasas
    ADD CONSTRAINT testasirasas_testasid_fkey FOREIGN KEY (testasid) REFERENCES public.testas(id) ON DELETE CASCADE;


-- Completed on 2026-08-11 15:22:01 EEST

--
-- PostgreSQL database dump complete
--

\unrestrict BqCH1rJ8H8hX3j5kIIinAfFNVWyUkTeaom6ZqEiT8937tUdjANwyLKxkE2ysEB2

